import express from 'express';
import { query } from '../config/db.js';
import { authenticateToken, requireTenantAccess } from '../middleware/auth.js';
import { isValidUUID } from '../middleware/validators.js';
import { canOperateCrmLead, canWriteCrm } from '../services/crm-permissions.js';
import { queueLeadQualification } from '../services/lead-qualification-runner.js';

const router = express.Router();
router.use(authenticateToken);
const roles = (req) => ({ systemRole: req.user.system_role, tenantRole: req.verified_tenant_role, userId: req.user.user_id });
const page = (req, res) => { const limit = Number(req.query.limit ?? 25), offset = Number(req.query.offset ?? 0); if (!Number.isInteger(limit) || limit < 1 || limit > 100 || !Number.isInteger(offset) || offset < 0) { res.status(400).json({ error: 'limit must be 1-100 and offset must be non-negative' }); return null; } return { limit, offset }; };
const id = (value) => typeof value === 'string' && isValidUUID(value);
const tenant = (req) => req.verified_tenant_id;
const write = (req, res) => { if (!canWriteCrm(roles(req))) { res.status(403).json({ error: 'CRM write access required' }); return false; } return true; };
async function leadForTenant(tenantId, leadId) { const r = await query('SELECT * FROM crm_leads WHERE tenant_id = $1 AND id = $2', [tenantId, leadId]); return r.rows[0] ?? null; }
function error(res, err) { if (err?.code === '23503') return res.status(409).json({ error: 'Referenced CRM resource is not valid for this tenant' }); return res.status(500).json({ error: 'Server error' }); }

router.get('/:tenantId/leads', requireTenantAccess, async (req,res) => { const p=page(req,res); if(!p)return; const t=tenant(req); const values=[t], where=['l.tenant_id = $1']; if(req.query.temperature){ if(!['HOT','WARM','COLD','UNQUALIFIED'].includes(req.query.temperature))return res.status(400).json({error:'Invalid temperature'}); values.push(req.query.temperature);where.push(`l.temperature = $${values.length}`); } if(req.query.stage){ if(!id(req.query.stage))return res.status(400).json({error:'Invalid stage ID'});values.push(req.query.stage);where.push(`l.pipeline_stage_id = $${values.length}`);} if(req.query.assigned_user_id){if(!id(req.query.assigned_user_id))return res.status(400).json({error:'Invalid assigned user ID'});values.push(req.query.assigned_user_id);where.push(`l.assigned_user_id = $${values.length}`);} values.push(p.limit,p.offset); try { const r=await query(`SELECT l.*, c.display_name,c.email,c.phone,s.name AS pipeline_stage,s.stage_key,u.email AS assigned_user_email,COUNT(*) OVER() AS total FROM crm_leads l JOIN crm_contacts c ON c.id=l.contact_id AND c.tenant_id=l.tenant_id JOIN crm_pipeline_stages s ON s.id=l.pipeline_stage_id AND s.tenant_id=l.tenant_id LEFT JOIN users u ON u.id=l.assigned_user_id WHERE ${where.join(' AND ')} ORDER BY l.last_activity_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values); return res.json({items:r.rows,total:Number(r.rows[0]?.total??0),...p}); }catch(e){return error(res,e);} });

router.post('/:tenantId/leads', requireTenantAccess, async (req,res)=>{if(!write(req,res))return; const t=tenant(req),b=req.body??{}; if(!id(b.contact_id))return res.status(400).json({error:'Valid contact_id is required'}); if(b.company_id && !id(b.company_id))return res.status(400).json({error:'Invalid company_id'}); if(b.conversation_id && !id(b.conversation_id))return res.status(400).json({error:'Invalid conversation_id'}); try { const stage=b.pipeline_stage_id|| (await query(`SELECT id FROM crm_pipeline_stages WHERE tenant_id=$1 AND stage_key='NEW_LEAD'`,[t])).rows[0]?.id; if(!stage)return res.status(409).json({error:'Default pipeline is unavailable'}); const r=await query(`INSERT INTO crm_leads (tenant_id,contact_id,company_id,conversation_id,source_channel,pipeline_stage_id,intent,service_interest) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[t,b.contact_id,b.company_id??null,b.conversation_id??null,b.source_channel??null,stage,b.intent??null,b.service_interest??null]); return res.status(201).json(r.rows[0]); }catch(e){return error(res,e);} });

router.get('/:tenantId/leads/:leadId', requireTenantAccess, async(req,res)=>{if(!id(req.params.leadId))return res.status(400).json({error:'Invalid lead ID'});try{const r=await query(`SELECT l.*,c.first_name,c.last_name,c.display_name,c.email,c.phone,c.language,c.country,s.name AS pipeline_stage,s.stage_key,u.email AS assigned_user_email FROM crm_leads l JOIN crm_contacts c ON c.id=l.contact_id AND c.tenant_id=l.tenant_id JOIN crm_pipeline_stages s ON s.id=l.pipeline_stage_id AND s.tenant_id=l.tenant_id LEFT JOIN users u ON u.id=l.assigned_user_id WHERE l.tenant_id=$1 AND l.id=$2`,[tenant(req),req.params.leadId]);if(!r.rowCount)return res.status(404).json({error:'Lead not found'});return res.json(r.rows[0]);}catch(e){return error(res,e)}});

router.put('/:tenantId/leads/:leadId', requireTenantAccess, async(req,res)=>{if(!write(req,res))return;if(!id(req.params.leadId))return res.status(400).json({error:'Invalid lead ID'});const b=req.body??{};try{const r=await query(`UPDATE crm_leads SET intent=COALESCE($1,intent),service_interest=COALESCE($2,service_interest),budget_text=COALESCE($3,budget_text),timeline=COALESCE($4,timeline),updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$5 AND id=$6 RETURNING *`,[b.intent??null,b.service_interest??null,b.budget_text??null,b.timeline??null,tenant(req),req.params.leadId]);if(!r.rowCount)return res.status(404).json({error:'Lead not found'});return res.json(r.rows[0]);}catch(e){return error(res,e)}});

router.post('/:tenantId/leads/:leadId/rescore', requireTenantAccess, async(req,res)=>{if(!write(req,res))return;if(!id(req.params.leadId))return res.status(400).json({error:'Invalid lead ID'});const lead=await leadForTenant(tenant(req),req.params.leadId);if(!lead)return res.status(404).json({error:'Lead not found'});if(!lead.conversation_id)return res.status(409).json({error:'Lead has no conversation to rescore'});queueLeadQualification({tenantId:tenant(req),conversationId:lead.conversation_id,force:true});return res.status(202).json({status:'queued',lead_id:lead.id});});

router.post('/:tenantId/leads/:leadId/assign', requireTenantAccess, async(req,res)=>{if(!write(req,res))return;if(!id(req.params.leadId)||!id(req.body?.user_id))return res.status(400).json({error:'Valid lead and user IDs are required'});try{const t=tenant(req),member=await query('SELECT user_id FROM tenant_users WHERE tenant_id=$1 AND user_id=$2',[t,req.body.user_id]);if(!member.rowCount)return res.status(404).json({error:'Tenant user not found'});const r=await query('UPDATE crm_leads SET assigned_user_id=$1,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$2 AND id=$3 RETURNING *',[req.body.user_id,t,req.params.leadId]);if(!r.rowCount)return res.status(404).json({error:'Lead not found'});return res.json(r.rows[0]);}catch(e){return error(res,e)}});

router.post('/:tenantId/leads/:leadId/stage', requireTenantAccess, async(req,res)=>{if(!id(req.params.leadId)||!id(req.body?.pipeline_stage_id))return res.status(400).json({error:'Valid lead and pipeline_stage IDs are required'});try{const t=tenant(req),lead=await leadForTenant(t,req.params.leadId);if(!lead)return res.status(404).json({error:'Lead not found'});if(!canOperateCrmLead({...roles(req),action:'stage',assignedUserId:lead.assigned_user_id}))return res.status(403).json({error:'Lead stage update is not permitted'});const stage=await query('SELECT * FROM crm_pipeline_stages WHERE tenant_id=$1 AND id=$2',[t,req.body.pipeline_stage_id]);if(!stage.rowCount)return res.status(404).json({error:'Pipeline stage not found'});const r=await query(`UPDATE crm_leads SET pipeline_stage_id=$1,status=CASE WHEN $2='WON' THEN 'converted' WHEN $2='LOST' THEN 'closed' ELSE status END,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$3 AND id=$4 RETURNING *`,[stage.rows[0].id,stage.rows[0].stage_key,t,lead.id]);return res.json(r.rows[0]);}catch(e){return error(res,e)}});

router.get('/:tenantId/contacts',requireTenantAccess,async(req,res)=>{const p=page(req,res);if(!p)return;try{const r=await query('SELECT *,COUNT(*) OVER() AS total FROM crm_contacts WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2 OFFSET $3',[tenant(req),p.limit,p.offset]);res.json({items:r.rows,total:Number(r.rows[0]?.total??0),...p});}catch(e){error(res,e)}});
router.get('/:tenantId/contacts/:contactId',requireTenantAccess,async(req,res)=>{if(!id(req.params.contactId))return res.status(400).json({error:'Invalid contact ID'});const r=await query('SELECT * FROM crm_contacts WHERE tenant_id=$1 AND id=$2',[tenant(req),req.params.contactId]);if(!r.rowCount)return res.status(404).json({error:'Contact not found'});res.json(r.rows[0]);});
router.get('/:tenantId/companies',requireTenantAccess,async(req,res)=>{const p=page(req,res);if(!p)return;const r=await query('SELECT *,COUNT(*) OVER() AS total FROM crm_companies WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2 OFFSET $3',[tenant(req),p.limit,p.offset]);res.json({items:r.rows,total:Number(r.rows[0]?.total??0),...p});});
router.get('/:tenantId/pipelines',requireTenantAccess,async(req,res)=>{const r=await query('SELECT * FROM crm_pipeline_stages WHERE tenant_id=$1 ORDER BY position',[tenant(req)]);res.json(r.rows);});
router.get('/:tenantId/deals',requireTenantAccess,async(req,res)=>{const p=page(req,res);if(!p)return;const r=await query('SELECT d.*,l.contact_id,s.name AS pipeline_stage,COUNT(*) OVER() AS total FROM crm_deals d JOIN crm_leads l ON l.id=d.lead_id AND l.tenant_id=d.tenant_id JOIN crm_pipeline_stages s ON s.id=d.pipeline_stage_id AND s.tenant_id=d.tenant_id WHERE d.tenant_id=$1 ORDER BY d.updated_at DESC LIMIT $2 OFFSET $3',[tenant(req),p.limit,p.offset]);res.json({items:r.rows,total:Number(r.rows[0]?.total??0),...p});});
router.post('/:tenantId/deals',requireTenantAccess,async(req,res)=>{if(!write(req,res))return;const b=req.body??{};if(!id(b.lead_id)||!id(b.pipeline_stage_id)||typeof b.title!=='string'||!b.title.trim())return res.status(400).json({error:'lead_id, pipeline_stage_id and title are required'});try{const r=await query('INSERT INTO crm_deals (tenant_id,lead_id,title,pipeline_stage_id,value,currency,expected_close_date,owner_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[tenant(req),b.lead_id,b.title.trim(),b.pipeline_stage_id,b.value??null,b.currency??null,b.expected_close_date??null,b.owner_user_id??null]);res.status(201).json(r.rows[0]);}catch(e){error(res,e)}});
router.put('/:tenantId/deals/:dealId',requireTenantAccess,async(req,res)=>{if(!write(req,res))return;if(!id(req.params.dealId))return res.status(400).json({error:'Invalid deal ID'});const b=req.body??{};try{const r=await query('UPDATE crm_deals SET title=COALESCE($1,title),pipeline_stage_id=COALESCE($2,pipeline_stage_id),value=COALESCE($3,value),currency=COALESCE($4,currency),expected_close_date=COALESCE($5,expected_close_date),updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$6 AND id=$7 RETURNING *',[b.title??null,b.pipeline_stage_id??null,b.value??null,b.currency??null,b.expected_close_date??null,tenant(req),req.params.dealId]);if(!r.rowCount)return res.status(404).json({error:'Deal not found'});res.json(r.rows[0]);}catch(e){error(res,e)}});
export default router;

