import { useEffect, useState, type FormEvent } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { onboardingApi } from '../dashboard/dashboard-api';

export function ResetPasswordPage() {
  const [params] = useSearchParams(); const navigate = useNavigate();
  const [token] = useState(() => params.get('token') ?? ''); const [valid, setValid] = useState<boolean | null>(null);
  const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [done, setDone] = useState(false);
  useEffect(() => { if (window.location.search) window.history.replaceState({}, '', window.location.pathname); if (!token) { setValid(false); return; } void onboardingApi.validatePasswordReset(token).then(() => setValid(true)).catch(() => setValid(false)); }, [token]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (password.length < 8 || password.length > 256 || password !== confirm) { setError('Use matching passwords between 8 and 256 characters.'); return; } try { await onboardingApi.consumePasswordReset({ token, password, confirm_password: confirm }); setDone(true); setTimeout(() => navigate('/login', { replace: true }), 1500); } catch { setError('This reset link is unavailable.'); } };
  if (valid === null) return <main className="grid min-h-screen place-items-center bg-[#0B0B0D] text-stone-300">Checking reset link…</main>;
  if (!valid) return <main className="grid min-h-screen place-items-center bg-[#0B0B0D] px-5 text-white"><section className="w-full max-w-md rounded-2xl border border-white/15 bg-[#161618] p-7"><h1 className="text-2xl font-semibold">Reset link unavailable</h1><p className="mt-3 text-sm text-stone-300">Request a new password reset from sign in.</p><button onClick={() => navigate('/login')} className="mt-6 rounded-xl bg-signal px-4 py-2.5 text-sm font-semibold">Go to sign in</button></section></main>;
  return <main className="grid min-h-screen place-items-center bg-[#0B0B0D] px-5 text-white"><section className="w-full max-w-md rounded-2xl border border-white/15 bg-[#161618] p-7"><h1 className="text-2xl font-semibold">Reset your password</h1>{done ? <p className="mt-4 text-sm text-stone-300">Password updated. Redirecting to sign in…</p> : <form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm">New password<input aria-label="New password" type="password" autoComplete="new-password" value={password} onChange={e => setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-white/20 bg-black/20 px-3 py-3" /></label><label className="block text-sm">Confirm password<input aria-label="Confirm password" type="password" autoComplete="new-password" value={confirm} onChange={e => setConfirm(e.target.value)} className="mt-2 w-full rounded-xl border border-white/20 bg-black/20 px-3 py-3" /></label>{error && <p role="alert" className="text-sm text-red-200">{error}</p>}<button className="w-full rounded-xl bg-signal px-4 py-3 font-semibold">Reset password</button></form>}</section></main>;
}
