import { useQuery } from '@tanstack/react-query';
import { Bot, CalendarDays, CheckSquare, CircleDollarSign, Clock3, MessageCircle, MessagesSquare, Sparkles, UsersRound, Zap } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { EmptyState, QueryErrorState, SkeletonBlock } from '../../components/ui/async-state';
import type { DashboardOverview } from '../../types/api';
import { tenantApi, tenantKeys } from '../dashboard/dashboard-api';
import { useTenant } from '../tenants/tenant-context';

const channelColors: Record<string, string> = { WHATSAPP: '#18b86d', WEB_CHAT: '#e4343c', SAMCHEGUIDE: '#7767f6' };
const channelName = (channel?: string | null) => channel === 'WEB_CHAT' ? 'Web Chatbot' : channel === 'SAMCHEGUIDE' ? 'AI Guide' : channel === 'WHATSAPP' ? 'WhatsApp' : '—';
const compactDate = (value: string) => new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(new Date(value));
const relativeTime = (value?: string | null) => { if (!value) return '—'; const diff = Math.max(0, Date.now() - new Date(value).getTime()); const m = Math.floor(diff / 60000); return m < 1 ? 'Now' : m < 60 ? m + 'm ago' : m < 1440 ? Math.floor(m / 60) + 'h ago' : Math.floor(m / 1440) + 'd ago'; };
export const formatOverviewValue = (value: number | null, suffix = '') => value === null ? '—' : value + suffix;
export const overviewWorkspaceName = (name?: string) => name || 'your workspace';

function MiniTrend({ trend }: { trend: number | null }) { return trend === null ? <span className="text-[11px] text-stone-500">Not enough data</span> : <span className={trend >= 0 ? 'text-[11px] text-emerald-400' : 'text-[11px] text-red-300'}>{trend >= 0 ? '↑' : '↓'} {Math.abs(trend)}% vs prior period</span>; }
function LineChart({ series }: { series: DashboardOverview['conversation_timeseries'] }) {
  const max = Math.max(...series.map((item) => item.count), 1);
  const points = series.map((item, index) => [series.length === 1 ? 0 : (index / (series.length - 1)) * 100, 100 - (item.count / max) * 86] as const);
  const line = points.map(([x, y]) => x + ',' + y).join(' ');
  return <div className="mt-4"><div className="h-52 rounded-lg border border-line/70 bg-[#09101a] p-3"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full overflow-visible" aria-label="Conversations over time"><defs><linearGradient id="overview-red-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#e3343d" stopOpacity=".32" /><stop offset="100%" stopColor="#e3343d" stopOpacity="0" /></linearGradient></defs>{points.length > 0 && <><polygon points={'0,100 ' + line + ' 100,100'} fill="url(#overview-red-fill)" /><polyline points={line} fill="none" stroke="#ef343d" strokeWidth="1.5" vectorEffect="non-scaling-stroke" /></>}<line x1="0" y1="100" x2="100" y2="100" stroke="#263448" vectorEffect="non-scaling-stroke" /></svg></div><div className="mt-2 flex justify-between text-[10px] text-stone-500">{series.length ? <><span>{compactDate(series[0].day)}</span><span>{compactDate(series[series.length - 1].day)}</span></> : <span>No conversation activity for this range.</span>}</div></div>;
}
function Donut({ distribution }: { distribution: DashboardOverview['channel_distribution'] }) {
  const total = distribution.reduce((sum, item) => sum + item.count, 0);
  let cursor = 0; const colors = distribution.map((item) => { const start = cursor; cursor += total ? (item.count / total) * 100 : 0; return (channelColors[item.channel] ?? '#d7a330') + ' ' + start + '% ' + cursor + '%'; });
  return <div className="mt-5 flex items-center gap-5"><div className="grid h-36 w-36 shrink-0 place-items-center rounded-full" style={{ background: total ? 'conic-gradient(' + colors.join(',') + ')' : '#172234' }}><div className="grid h-20 w-20 place-items-center rounded-full bg-panel text-center"><span className="text-xl font-semibold text-ink">{total || '—'}</span><span className="text-[9px] uppercase tracking-wider text-stone-500">Total</span></div></div><ul className="min-w-0 flex-1 space-y-2">{distribution.length ? distribution.map((item) => <li key={item.channel} className="flex items-center justify-between gap-2 text-xs"><span className="flex min-w-0 items-center gap-2 text-stone-300"><i className="h-2 w-2 rounded-full" style={{ background: channelColors[item.channel] ?? '#d7a330' }} />{channelName(item.channel)}</span><span className="text-stone-500">{Math.round((item.count / total) * 100)}%</span></li>) : <li className="text-xs text-stone-500">No channel activity yet.</li>}</ul></div>;
}
export function OverviewPage() {
  const { selectedTenant } = useTenant(); const tenantId = selectedTenant?.id ?? ''; const [days, setDays] = useState(7);
  const query = useQuery({ queryKey: tenantKeys.dashboardOverview(tenantId, days), queryFn: () => tenantApi.getDashboardOverview(tenantId, days), enabled: Boolean(tenantId) });
  if (!tenantId) return <EmptyState title="No tenant selected" description="Choose a tenant to view its workspace data." />;
  if (query.isLoading) return <div className="space-y-4"><SkeletonBlock className="h-20 w-80" /><SkeletonBlock className="h-32" /><SkeletonBlock className="h-80" /></div>;
  if (query.isError) return <QueryErrorState error={query.error} onRetry={() => void query.refetch()} resource="dashboard analytics" />;
  const data = query.data!; const kpis = [
    ['Total Conversations', data.kpis.total_conversations, MessagesSquare], ['New Leads', data.kpis.new_leads, UsersRound],
    ['Appointments', data.kpis.appointments, CalendarDays], ['Automations', data.kpis.automations, Zap], ['Satisfaction Rate', data.kpis.satisfaction_rate, CheckSquare],
  ] as const; const maxIntent = Math.max(...data.top_intents.map((item) => item.count), 1);
  return <div className="mx-auto max-w-[1450px] space-y-4 pb-5">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight text-ink">Dashboard Overview</h1><p className="mt-1 text-sm text-stone-400">Welcome back, {overviewWorkspaceName(selectedTenant?.name)}. Here’s what’s happening with your AI platform today.</p></div><select value={days} onChange={(event) => setDays(Number(event.target.value))} className="field w-auto text-xs" aria-label="Analytics period"><option value={7}>This week</option><option value={30}>Last 30 days</option></select></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{kpis.map(([label, value, Icon]) => <article key={label} className="dashboard-card min-h-[116px] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-medium text-stone-400">{label}</p><p className="mt-1.5 text-2xl font-semibold tracking-tight text-ink">{value === null ? '—' : value}{label === 'Satisfaction Rate' && value !== null ? '%' : ''}</p></div><span className="grid h-9 w-9 place-items-center rounded-full bg-signal-soft text-signal"><Icon size={17} /></span></div><div className="mt-3"><MiniTrend trend={label === 'Total Conversations' ? data.kpis.conversation_growth : null} /></div></article>)}</section>
    <section className="grid gap-3 xl:grid-cols-[1.75fr_1fr]"><article className="dashboard-card p-4"><div className="flex justify-between gap-3"><h2 className="text-sm font-semibold text-ink">Conversations Over Time</h2><span className="text-xs text-stone-500">{days === 7 ? 'This week' : 'Last 30 days'}</span></div><LineChart series={data.conversation_timeseries} /></article><article className="dashboard-card p-4"><h2 className="text-sm font-semibold text-ink">Top Channels</h2><Donut distribution={data.channel_distribution} /></article></section>
    <section className="grid gap-3 xl:grid-cols-[1.25fr_.8fr_1.1fr]"><article className="dashboard-card overflow-hidden"><header className="border-b border-line px-4 py-3"><h2 className="text-sm font-semibold text-ink">Recent Conversations</h2></header>{data.recent_conversations.length ? <ul className="divide-y divide-line">{data.recent_conversations.map((item) => <li key={item.id}><Link to={'/app/' + tenantId + '/conversations/whatsapp/' + item.id} className="flex items-center gap-3 px-4 py-3 hover:bg-white/[.025]"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-elevated text-xs font-semibold text-stone-300">{item.contact_name.slice(0, 1).toUpperCase()}</span><span className="min-w-0 flex-1"><b className="block truncate text-xs text-ink">{item.contact_name}</b><span className="block truncate text-[11px] text-stone-500">{item.last_message_preview || 'No message preview'}</span></span><span className="text-right text-[10px] text-stone-500">{relativeTime(item.last_activity_at)}</span></Link></li>)}</ul> : <p className="p-5 text-sm text-stone-500">No conversations yet.</p>}</article>
      <article className="dashboard-card p-4"><h2 className="text-sm font-semibold text-ink">AI Performance</h2><div className="mt-5 grid grid-cols-2 gap-x-5 gap-y-6">{[['Response Rate', formatOverviewValue(data.ai_performance.response_rate, '%')], ['Average Response Time', data.ai_performance.average_response_time_ms === null ? '—' : (data.ai_performance.average_response_time_ms / 1000).toFixed(1) + 's'], ['Resolution Rate', formatOverviewValue(data.ai_performance.containment_rate, '%')], ['Customer Satisfaction', formatOverviewValue(data.ai_performance.satisfaction_rate, '%')]].map(([label, value]) => <div key={label}><p className="text-[10px] text-stone-500">{label}</p><p className="mt-1 text-xl font-semibold text-ink">{value}</p><div className="mt-3 h-px bg-gradient-to-r from-signal via-signal/30 to-transparent" /></div>)}</div></article>
      <article className="dashboard-card p-4"><h2 className="text-sm font-semibold text-ink">Top Intents</h2>{data.top_intents.length ? <div className="mt-5 space-y-3">{data.top_intents.map((item) => <div key={item.label}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate text-stone-300">{item.label}</span><span className="text-stone-500">{item.count}</span></div><div className="h-1.5 rounded-full bg-elevated"><div className="h-full rounded-full bg-signal" style={{ width: (item.count / maxIntent) * 100 + '%' }} /></div></div>)}</div> : <p className="mt-5 text-sm text-stone-500">No intent data yet.</p>}</article></section>
    <section className="dashboard-card grid gap-3 p-4 md:grid-cols-[1.4fr_repeat(4,1fr)]"><div className="flex items-center gap-3 border-b border-line pb-3 md:border-b-0 md:border-r md:pb-0"><span className="grid h-10 w-10 place-items-center rounded-full bg-signal-soft text-signal"><Sparkles size={19} /></span><div><p className="text-sm font-semibold text-ink">AI Insights</p><p className="text-xs text-stone-500">Tenant activity based on the selected range.</p></div></div>{[['Peak Time', data.insights.peak_hour], ['Best Channel', channelName(data.insights.best_channel)], ['Top Performing Bot', data.insights.top_assistant], ['Growth', data.insights.growth === null ? null : data.insights.growth + '%']].map(([label, value]) => <div key={label} className="flex items-center gap-2"><Clock3 size={16} className="text-stone-500" /><div><p className="text-[10px] uppercase tracking-wider text-stone-500">{label}</p><p className="text-sm font-medium text-ink">{value || '—'}</p></div></div>)}</section>
  </div>;
}
