import { Building2, CalendarDays, LogOut, Menu } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import type { Tenant } from '../../types/api';
import { useOverviewDateRange } from '../../features/overview/overview-date-range-context';
interface TopbarProps { tenants: Tenant[]; selectedTenantId: string; email: string; onSelectTenant(tenantId: string): void; onOpenNavigation(): void; onLogout(): void; }
export function Topbar({ tenants, selectedTenantId, email, onSelectTenant, onOpenNavigation, onLogout }: TopbarProps) {
  const location = useLocation();
  const { preset, setPreset, customStart, setCustomStart, customEnd, setCustomEnd, activeRange } = useOverviewDateRange();
  const knownSection = location.pathname.split('/').find((segment) => ['overview', 'conversations', 'leads', 'pipeline', 'assistants', 'channels', 'knowledge-base', 'team', 'settings'].includes(segment));
  const title = ({ overview: 'Dashboard Overview', conversations: 'Conversations', leads: 'Leads', pipeline: 'Pipeline', assistants: 'AI Assistants', channels: 'Channels', 'knowledge-base': 'Knowledge Base', team: 'Team', settings: 'Settings' } as Record<string, string>)[knownSection ?? ''] ?? 'Dashboard Overview';
  const isOverview = knownSection === 'overview';
  return <header className="flex min-h-[4.25rem] items-center justify-between border-b border-line/80 bg-shell/85 px-4 backdrop-blur-xl sm:px-6 lg:px-7">
    <div className="flex min-w-0 items-center gap-3"><button type="button" onClick={onOpenNavigation} className="grid h-10 w-10 place-items-center rounded-lg text-stone-300 hover:bg-white/[0.04] lg:hidden" aria-label="Open navigation"><Menu aria-hidden="true" size={21} /></button><p className="truncate text-lg font-semibold tracking-tight text-ink sm:text-xl">{title}</p></div>
    <div className="flex items-center gap-3">{isOverview && <div className="glass-surface hidden items-center gap-2 rounded-xl p-2 xl:flex"><CalendarDays size={15} className="text-signal" /><select value={preset} onChange={(event) => setPreset(event.target.value as typeof preset)} className="border-0 !bg-transparent px-1 text-xs font-semibold outline-none" aria-label="Dashboard date range"><option value="today">Today</option><option value="last-7-days">Last 7 days</option><option value="last-30-days">Last 30 days</option><option value="this-month">This month</option><option value="custom">Custom range</option></select>{preset === 'custom' && <><input aria-label="Dashboard range start" type="date" value={customStart} max={customEnd} onChange={(event) => setCustomStart(event.target.value)} className="max-w-32 rounded-md bg-transparent px-1 text-[11px]" /><span className="text-[11px] text-stone-500">to</span><input aria-label="Dashboard range end" type="date" value={customEnd} min={customStart} onChange={(event) => setCustomEnd(event.target.value)} className="max-w-32 rounded-md bg-transparent px-1 text-[11px]" /></>}<span className="rounded-md bg-white/[.04] px-1.5 py-1 text-[10px] text-stone-400">{activeRange.label}</span></div>}<div className="glass-surface min-w-0 rounded-xl px-3 py-2"><label className="sr-only" htmlFor="tenant-select">Selected tenant</label><span className="mr-2 inline-block align-middle text-signal"><Building2 aria-hidden="true" size={15} /></span><select id="tenant-select" value={selectedTenantId} onChange={(event) => onSelectTenant(event.target.value)} className="max-w-40 truncate bg-transparent text-sm font-semibold text-ink outline-none sm:max-w-56">{tenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.name}</option>)}</select></div><span className="hidden max-w-48 truncate text-xs text-stone-400 xl:block" title={email}>{email}</span><button type="button" onClick={onLogout} className="grid h-10 w-10 place-items-center rounded-xl border border-line bg-elevated/60 text-stone-400 transition hover:border-signal/30 hover:text-ink" aria-label="Sign out"><LogOut aria-hidden="true" size={18} /></button></div>
  </header>;
}
